### PR TITLE
Master fhe perf lul

### PR DESCRIPTION
**Pull request by LucasLefevre**
## Description:

description of this task, what is implemented and why it is implemented that way.

Task: [TASK_ID](https://www.odoo.com/web#id=TASK_ID&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

### CODE REVIEW

**Comment by laa-odoo** [comment]
in this case you might as well remove the return types from all the formulas, right? having a transient state where you don't know when you develop a formula whether you should put a return type or not will annoy me

**Comment by laa-odoo** [comment]
if the goal is to gain performance this way. Might consider reviewing how the casting function returns the error as well

**Comment by laa-odoo** [comment]
also in this approach I wonder when you replace that

```typescript
throw new EvaluationError(_t("The number of columns must be positive."));
```
by
```typescript
return new EvaluationError(_t("The number of columns must be positive."));
```
Wouldn't replacing instead with that also make it possible to gain more? 

```typescript
return  {value: CellErrorType.GenericError, message: _t("The number of columns must be positive.")}
```

(in any case this would allow us to keep a typing on the return of the function)

**Comment by LucasLefevre** [comment]
> in this case you might as well remove the return types from all the formulas, right? having a transient state where you don't know when you develop a formula whether you should put a return type or not will annoy me

IMO return types are useful when they help, but can be omitted if it's too lengthy and we can let Typescript infer it

**Comment by LucasLefevre** [comment]
> if the goal is to gain performance this way, might consider reviewing how the casting function returns the error as well

Any idea ? I only converted "easy" ones

**Comment by LucasLefevre** [comment]
> Wouldn't replacing instead with that also make it possible to gain more?
return  {value: CellErrorType.GenericError, message: _t("The number of columns must be positive.")}

probably yes (especially given EvaluationError extends Error). But it's so much shorter and nicer with `return new EvaluationError()` :cry: 

> (in any case this would allow us to keep a typing on the return of the function)

It would be the same. What's annoying is with mixed return types (matrices and simple value/error)

**Comment by laa-odoo** [comment]
> > if the goal is to gain performance this way, might consider reviewing how the casting function returns the error as well
> 
> Any idea ? I only converted "easy" ones


open task to do this :)
https://www.odoo.com/odoo/project/2328/tasks/4208351

**Comment by LucasLefevre** [comment]
robodoo rebase-ff

**Pull request closed without merging**
