### PR TITLE
Master recompute zones everywhere laa

### PR DESCRIPTION
**Pull request by laa-odoo**
## [REF] recompute zones: use recomputeZones on missing places
For performance reasons, this commit proposes to add
recomputeZonnes wherever we cross all the elements of
a list of zones.

## [REF] zones helper: remove unused helpers

Task: [3893550](https://www.odoo.com/web#id=3893550&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

### CODE REVIEW

**Review by rrahir — CHANGES_REQUESTED** [review]
A little rebase is in order :/
I think we could add the use of recompute zone in a couple more places as well but there might be a reason you didn't. I'm thinking of
- DataValidationPlugin -> handle "DELETE_CONTENT"
- AutomaticSumPlugin -> handle "SUM_SELECTION"
- MergePlugin -> handle  "ADD_MERGE","REMOVE_MERGE"
What do you think of those?

**Comment by laa-odoo** [comment]
> * ADD_MERGE

Ok with `DELETE_CONTENT` on DataValidationPlugin

For the others, the behavior can functionally change. So no

**Comment by laa-odoo** [comment]
> A little rebase is in order :/ I think we could add the use of recompute zone in a couple more places as well but there might be a reason you didn't. I'm thinking of
> 
> * DataValidationPlugin -> handle "DELETE_CONTENT"
> * AutomaticSumPlugin -> handle "SUM_SELECTION"
> * MergePlugin -> handle  "ADD_MERGE","REMOVE_MERGE"
>   What do you think of those?


Ok with `DELETE_CONTENT` on DataValidationPlugin

For the others, the behavior can functionally change. So no

**Comment by rrahir** [comment]
@robodoo rebase-ff

**Comment by rrahir** [comment]
Off we go then :D
@robodoo r+

**Pull request closed without merging**
