### PR TITLE
[IMP] spreadsheet: various fixes & imp

### PR DESCRIPTION
**Pull request by hokolomopo**
## Description:

Commits that were part of #4182 before it was cancelled

Not sure commit [[REF] clipboard: expose paste logic](https://github.com/odoo/o-spreadsheet/pull/4332/commits/8ec6ad2675e37fd6ceae9975b78cc39c56632e55) is something we want right now. The other commit all seems like good ideas

## [IMP] mergeContiguousZones: add test & fix diagonal
This commit moves the tests of mergeContiguousZones from Odoo
to o-spreadsheet.

It also fixes a bug where the algorithm was merging zones that were
diagonal to each other.

## [REF] clipboard: decouple clipboards and active sheet
This commit make the clipboards handlers independent from the active
sheet, thus allowing to use them to copy/paste things in any sheet.

## [FIX] evaluation: `getEvaluatedCells` with spreading cells
The getter `getEvaluatedCells` does't return spreaded cells. It
also returns empty evaluated cells that have some style.

This is not the expected behaviour. `getEvaluatedCells` should return
all the non-empty evaluated cells of a sheet.

Task: : [3965270](https://www.odoo.com/web#id=3965270&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

### CODE REVIEW

**Review by anhe-odoo — COMMENTED** [review]
LGTM except for the add of empty cell when pasting chart, to see with François :)

**Comment by rrahir** [comment]
As discussed, I think we should keep the commits with a real added value here: I think those are useful:
- https://github.com/odoo/o-spreadsheet/pull/4332/commits/bc5135f6ad10e3a804d63cfd933af77693d035b8
- https://github.com/odoo/o-spreadsheet/pull/4332/commits/9276cf2cca47c7267e14b68ecc61d8a475c9724b
- https://github.com/odoo/o-spreadsheet/pull/4332/commits/cbafe5fde868f5fe32e16b15179510a1e07b18b1

The other 3 can be dropped as they were helpful regarding the spec of https://github.com/odoo/o-spreadsheet/pull/4182 but meaningless by themselves

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
