### PR TITLE
[FIX] formula: fix LOGEST/LINEST descriptions

### PR DESCRIPTION
**Pull request by anhe-odoo**
## Description:

This PR aims to fix the description of the LOGEST and LINEST formulas, which were the same as the SLOPE formula.

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

### CODE REVIEW

**Comment by rrahir** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
robodoo r-

**Comment by LucasLefevre** [comment]
robodoo r+

**Comment by rrahir** [comment]
@robodoo r+

**Pull request closed without merging**
